FROM registry.gitlab.com/avanzainnovations/baseimage-ebi:rhel
#FROM risingstack/alpine:3.7-v8.10.0-4.8.0
MAINTAINER Avanza Innovations <bilal.mahroof@avanzainnovations.com>



#RUN adduser -S 1001

#WORKDIR /home/avanza
RUN bash -c "npm --version"
#RUN node -v
#RUN npm -v
#RUN bash -c "mkdir -p /home/1001/app/logs"
#RUN bash -c "mkdir -p /home/1001/app/dist"
WORKDIR /opt/app-root
COPY package.json .
COPY . .
RUN bash -c "npm install"
USER 1001
EXPOSE 9080
CMD ["node","app"]